version: 2
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint-scripts
          command: .circleci/lint-scripts.sh
  lint-chart:
    docker:
      - image: quay.io/helmpack/chart-testing:v2.1.0
    steps:
      - checkout
      - run:
          name: lint
          command: .circleci/lint-charts.sh
  install-chart:
    machine: true
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.1.0
      CHARTS_REPO: https://github.com/zammad/helm
    steps:
      - checkout
      - run:
          name: install
          command: .circleci/install.sh
          no_output_timeout: 3600
  deploy-chart:
    docker:
      - image: kiwigrid/gcloud-kubectl-helm:2.12.1-228.0.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "81:19:ad:15:3c:a5:a4:83:8f:41:68:a5:2c:be:f5:05"
      - checkout
      - run:
          name: deploy
          command: .circleci/deploy.sh
workflows:
  version: 2
  lint_install_deploy:
    jobs:
      - lint-scripts
      - lint-chart:
          requires:
            - lint-scripts
      - install-chart:
          requires:
            - lint-chart
      - deploy-chart:
          requires:
            - install-chart
