version: 2.1
jobs:
  lint-scripts:
    docker:
      - image: koalaman/shellcheck-alpine
    steps:
      - checkout
      - run:
          name: lint-scripts
          command: .circleci/lint-scripts.sh

  lint-chart:
    docker:
      - image: quay.io/helmpack/chart-testing:v2.2.0
    steps:
      - checkout
      - run:
          name: lint-chart
          command: .circleci/lint-chart.sh

  install-chart-k8s-1-11-3:
    machine: true
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.2.0
      CHARTS_REPO: https://github.com/kiwigrid/helm-charts
      KIND_VERSION: 0.1.0
      K8S_VERSION: v1.11.3
    steps:
      - checkout
      - run:
          name: install-chart-k8s-1-11-3
          command: .circleci/install-chart.sh
          no_output_timeout: 3600

  install-chart-k8s-1-12-3:
    machine: true
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.2.0
      CHARTS_REPO: https://github.com/kiwigrid/helm-charts
      KIND_VERSION: 0.1.0
      K8S_VERSION: v1.12.3
    steps:
      - checkout
      - run:
          name: install-chart-k8s-1-12-3
          command: .circleci/install-chart.sh
          no_output_timeout: 3600

  install-chart-k8s-1-13-2:
    machine: true
    environment:
      CHART_TESTING_IMAGE: quay.io/helmpack/chart-testing
      CHART_TESTING_TAG: v2.2.0
      CHARTS_REPO: https://github.com/kiwigrid/helm-charts
      KIND_VERSION: 0.1.0
      K8S_VERSION: v1.13.2
    steps:
      - checkout
      - run:
          name: install-chart-k8s-1-13-2
          command: .circleci/install-chart.sh
          no_output_timeout: 3600

  deploy-chart:
    docker:
      - image: kiwigrid/gcloud-kubectl-helm:2.14.1-249.0.0-148
    steps:
      - add_ssh_keys:
          fingerprints:
            - "81:19:ad:15:3c:a5:a4:83:8f:41:68:a5:2c:be:f5:05"
      - checkout
      - run:
          name: deploy
          command: .circleci/deploy-chart.sh

workflows:
  version: 2
  lint_install_deploy:
    jobs:
      - lint-scripts
      - lint-chart:
          requires:
            - lint-scripts
      - install-chart-k8s-1-11-3:
          requires:
            - lint-chart
      - install-chart-k8s-1-12-3:
          requires:
            - lint-chart
      - install-chart-k8s-1-13-2:
          requires:
            - lint-chart
      - deploy-chart:
          requires:
            - install-chart-k8s-1-11-3
            - install-chart-k8s-1-12-3
            - install-chart-k8s-1-13-2
